/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package libreria;

import Compra.jpListaPedidos;

import Compra.jpNuevoPedido;
import Compra.jpProveedores;
import Empleados.ABMTipoUsuario;
import Empleados.ConsultaUsuario;
import Empleados.TipoUsuario;
import Empleados.Usuario;
import Empleados.jpEstadoCivil;
import Empleados.jpCategoriaEmpleado;
import Empleados.jpEmpleados;
import Empleados.jpUsuario;
import Venta.BusquedaFactura;
import Venta.PanelCli;
import Venta.PanelListaFacturasVenta;
import Venta.TipoFactura;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import mapa.jpMapa;
import org.apache.commons.codec.digest.DigestUtils;
/**
 *
 * @author SEBASTIAN PAZ
 */
public class ventanaPrincipal extends javax.swing.JFrame {
 private Usuario usuario;
   private TipoUsuario tipousuario;
   private ConsultaUsuario consultaUsuario;
   private List<Usuario> usuarios = new ArrayList<>();
   private List<TipoUsuario> tu = new ArrayList<>();
   private int nivel;
    
   
    public ventanaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        consultaUsuario = new ConsultaUsuario();
        usuarios = consultaUsuario.getAllUsuario();
        System.out.println("cantidad="+usuarios.size());
        jLElegirOpcion.setVisible(false);
        if (usuarios.size() == 0)//Si no existe ningun usuario muestro campos de alta de usuario
                {
                    jTUsuarioNuevo.setVisible(true);
                    jTcontraseñaNueva.setVisible(true);
                    jBNuevoUsuario.setVisible(true);
                    jLNuevoUsuario.setVisible(true);
                    jLNuevaContraseña.setVisible(true);
                    jtfusuario.setText("admin");
                    jPcontraseña.setText("");
                    jBIngresar.setEnabled(false);
                    jtfusuario.setEnabled(false);
                    jPcontraseña.setEnabled(false);
                    
                }
        else
        {
                    jTUsuarioNuevo.setVisible(false);
                    jTcontraseñaNueva.setVisible(false);
                    jBNuevoUsuario.setVisible(false);
                    jLNuevoUsuario.setVisible(false);
                    jLNuevaContraseña.setVisible(false);
                    jBIngresar.setEnabled(true);
                    jtfusuario.setEnabled(true);
                    jPcontraseña.setEnabled(true);
                    jTContraseñaRepetida.setVisible(false);
                    jLRepetir.setVisible(false);
                    jLPrimerIngreso.setVisible(false);
        }
    }
    
    public void CargarPanel(JPanel panel){
        jPanelBase.removeAll();jPanelBase.repaint();jPanelBase.revalidate();
        jPanelBase.add(panel);jPanelBase.repaint();jPanelBase.revalidate();
    }
    
    @Override
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("recursos/quijote.png"));


        return retValue;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBtn = new javax.swing.JPanel();
        btnLibros = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnNueVenta = new javax.swing.JButton();
        jPanelBase = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLusuario = new javax.swing.JLabel();
        jLcontraseña = new javax.swing.JLabel();
        jtfusuario = new javax.swing.JTextField();
        jPcontraseña = new javax.swing.JPasswordField();
        jBIngresar = new javax.swing.JButton();
        jLBienvenidos = new javax.swing.JLabel();
        jLElegirOpcion = new javax.swing.JLabel();
        jLNuevoUsuario = new javax.swing.JLabel();
        jLNuevaContraseña = new javax.swing.JLabel();
        jLRepetir = new javax.swing.JLabel();
        jTUsuarioNuevo = new javax.swing.JTextField();
        jTcontraseñaNueva = new javax.swing.JPasswordField();
        jTContraseñaRepetida = new javax.swing.JPasswordField();
        jLPrimerIngreso = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBNuevoUsuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMTArchivo = new javax.swing.JMenu();
        jMCambiarUsuario = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenuItem();
        jMTSueldo = new javax.swing.JMenu();
        jmEmpleados = new javax.swing.JMenuItem();
        jmEstadosCiviles = new javax.swing.JMenuItem();
        jmCategorias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmiAutores1 = new javax.swing.JMenuItem();
        jmiGeneros1 = new javax.swing.JMenuItem();
        jmiEditoriales1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiProveedor = new javax.swing.JMenuItem();
        jmPedidos = new javax.swing.JMenu();
        jmNuevoPedido = new javax.swing.JMenu();
        jmiPedidoManual = new javax.swing.JMenuItem();
        jmiPedidoAuto = new javax.swing.JMenuItem();
        jmiListaPedido = new javax.swing.JMenuItem();
        jmMapa = new javax.swing.JMenu();
        jmiProvincia = new javax.swing.JMenuItem();
        jmiLocalidades = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Quijote");
        setIconImage(getIconImage());

        jPanelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanelBtn.setLayout(new org.jdesktop.swingx.VerticalLayout());

        btnLibros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/libros.png"))); // NOI18N
        btnLibros.setText("Libros");
        btnLibros.setEnabled(false);
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        jPanelBtn.add(btnLibros);

        btnCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cliente.png"))); // NOI18N
        btnCliente.setText("Clientes");
        btnCliente.setEnabled(false);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanelBtn.add(btnCliente);

        btnNueVenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNueVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/norden.png"))); // NOI18N
        btnNueVenta.setText("Nueva Venta");
        btnNueVenta.setEnabled(false);
        btnNueVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueVentaActionPerformed(evt);
            }
        });
        jPanelBtn.add(btnNueVenta);

        jPanelBase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        jPanelBase.setLayout(new java.awt.CardLayout());

        jLusuario.setText("Usuario");

        jLcontraseña.setText("Contraseña");

        jBIngresar.setText("Ingresar");
        jBIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarActionPerformed(evt);
            }
        });

        jLBienvenidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLBienvenidos.setText("Bienvenidos a El Quijote");

        jLElegirOpcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLElegirOpcion.setText("Elija una opcion para comenzar");

        jLNuevoUsuario.setText("Nuevo Usuario");

        jLNuevaContraseña.setText("Contraseña");

        jLRepetir.setText("Repetir Contraseña");

        jTUsuarioNuevo.setText("admin");

        jLPrimerIngreso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLPrimerIngreso.setText("Ingreso del primer usuario administrador");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Inicie Sesión Para Empezar");

        jBNuevoUsuario.setText("Nuevo Usuario");
        jBNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTUsuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLNuevaContraseña)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLRepetir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTcontraseñaNueva)
                            .addComponent(jTContraseñaRepetida, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jBNuevoUsuario))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(319, 319, 319)
                                .addComponent(jLcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jPcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLBienvenidos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jBIngresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLPrimerIngreso))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLElegirOpcion)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(270, 270, 270)
                    .addComponent(jLabel7)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLBienvenidos)
                .addGap(64, 64, 64)
                .addComponent(jLusuario)
                .addGap(18, 18, 18)
                .addComponent(jtfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLcontraseña)
                .addGap(18, 18, 18)
                .addComponent(jPcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLElegirOpcion)
                .addGap(18, 18, 18)
                .addComponent(jBIngresar)
                .addGap(13, 13, 13)
                .addComponent(jLPrimerIngreso)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTUsuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNuevoUsuario)
                    .addComponent(jLNuevaContraseña)
                    .addComponent(jTcontraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRepetir)
                    .addComponent(jTContraseñaRepetida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBNuevoUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jLabel7)
                    .addContainerGap(398, Short.MAX_VALUE)))
        );

        jPanelBase.add(jPanel1, "card2");

        jMTArchivo.setText("Archivo");
        jMTArchivo.setEnabled(false);
        jMTArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTArchivoActionPerformed(evt);
            }
        });

        jMCambiarUsuario.setText("Cambiar Usuario");
        jMCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCambiarUsuarioActionPerformed(evt);
            }
        });
        jMTArchivo.add(jMCambiarUsuario);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMTArchivo.add(jMSalir);

        jMenuBar1.add(jMTArchivo);

        jMTSueldo.setText("Empleados");
        jMTSueldo.setEnabled(false);

        jmEmpleados.setText("Gestion De Empleados");
        jmEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEmpleadosActionPerformed(evt);
            }
        });
        jMTSueldo.add(jmEmpleados);

        jmEstadosCiviles.setText("Estados Civiles");
        jmEstadosCiviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEstadosCivilesActionPerformed(evt);
            }
        });
        jMTSueldo.add(jmEstadosCiviles);

        jmCategorias.setText("Categorias");
        jmCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCategoriasActionPerformed(evt);
            }
        });
        jMTSueldo.add(jmCategorias);

        jMenuBar1.add(jMTSueldo);

        jMenu4.setText("Ventas");
        jMenu4.setEnabled(false);

        jMenuItem2.setText("Lista De Facturas De Ventas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem4.setText("Clientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Libros");
        jMenu7.setEnabled(false);

        jmiAutores1.setText("Autores");
        jmiAutores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAutores1ActionPerformed(evt);
            }
        });
        jMenu7.add(jmiAutores1);

        jmiGeneros1.setText("Generos");
        jmiGeneros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGeneros1ActionPerformed(evt);
            }
        });
        jMenu7.add(jmiGeneros1);

        jmiEditoriales1.setText("Editoriales");
        jmiEditoriales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditoriales1ActionPerformed(evt);
            }
        });
        jMenu7.add(jmiEditoriales1);

        jMenuBar1.add(jMenu7);

        jMenu3.setText("Compras");
        jMenu3.setEnabled(false);

        jmiProveedor.setText("Proveedores");
        jmiProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProveedorActionPerformed(evt);
            }
        });
        jMenu3.add(jmiProveedor);

        jmPedidos.setText("Pedidos");

        jmNuevoPedido.setText("Nuevo Pedido");

        jmiPedidoManual.setText("Manual");
        jmiPedidoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPedidoManualActionPerformed(evt);
            }
        });
        jmNuevoPedido.add(jmiPedidoManual);

        jmiPedidoAuto.setText("Automatico");
        jmiPedidoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPedidoAutoActionPerformed(evt);
            }
        });
        jmNuevoPedido.add(jmiPedidoAuto);

        jmPedidos.add(jmNuevoPedido);

        jmiListaPedido.setText("Lista Pedidos");
        jmiListaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListaPedidoActionPerformed(evt);
            }
        });
        jmPedidos.add(jmiListaPedido);

        jMenu3.add(jmPedidos);

        jMenuBar1.add(jMenu3);

        jmMapa.setText("Mapa");
        jmMapa.setEnabled(false);

        jmiProvincia.setText("Provincias");
        jmiProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProvinciaActionPerformed(evt);
            }
        });
        jmMapa.add(jmiProvincia);

        jmiLocalidades.setText("Localidades");
        jmiLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLocalidadesActionPerformed(evt);
            }
        });
        jmMapa.add(jmiLocalidades);

        jMenuBar1.add(jmMapa);

        jMenu6.setText("Usuarios");
        jMenu6.setEnabled(false);

        jMenuItem8.setText("Gestion De Usuarios");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem9.setText("Tipos De Usuarios");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(jPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//BOTONLIBROS
    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        jpLibro plo = new jpLibro();
        CargarPanel(plo);
        
    }//GEN-LAST:event_btnLibrosActionPerformed
//BOTONCLIENTE
    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        PanelCli pc= new  PanelCli();
        CargarPanel(pc);
    }//GEN-LAST:event_btnClienteActionPerformed
//BOTONNUEVA VENTA
    private void btnNueVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueVentaActionPerformed
        PanelListaFacturasVenta pfv= new PanelListaFacturasVenta(); 
        CargarPanel(pfv);
    }//GEN-LAST:event_btnNueVentaActionPerformed

    private void jmiLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLocalidadesActionPerformed
        jpMapa pm= new  jpMapa(1);
        CargarPanel(pm);
    }//GEN-LAST:event_jmiLocalidadesActionPerformed

    private void jmiProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProvinciaActionPerformed
        jpMapa pm= new  jpMapa(0);
        CargarPanel(pm);
    }//GEN-LAST:event_jmiProvinciaActionPerformed

    private void jmEstadosCivilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEstadosCivilesActionPerformed
        jpEstadoCivil tf= new jpEstadoCivil();
        CargarPanel(tf);
    }//GEN-LAST:event_jmEstadosCivilesActionPerformed

    private void jmCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCategoriasActionPerformed
        jpCategoriaEmpleado tf= new jpCategoriaEmpleado();
        CargarPanel(tf);
    }//GEN-LAST:event_jmCategoriasActionPerformed

    private void jmEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEmpleadosActionPerformed
        jpEmpleados tf= new jpEmpleados(0);
        CargarPanel(tf);
    }//GEN-LAST:event_jmEmpleadosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        BusquedaFactura bf = new BusquedaFactura();
        CargarPanel(bf);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        PanelCli pc = new PanelCli();
        CargarPanel(pc);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jBIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarActionPerformed
        
        String nombre = jtfusuario.getText();
        String contraseña = jPcontraseña.getText();
        contraseña= DigestUtils.md5Hex(jPcontraseña.getText());

        if(consultaUsuario.comprobarUsuarioExiste(nombre))
        {
        usuario = consultaUsuario.getUsuarioPorUsuario(nombre);
        tipousuario = consultaUsuario.getTiposUsuarioPorId(usuario.getIdTipoUsuario());
        System.out.println(usuario.getUsuario()+"-"+tipousuario);
        if(usuario.getContraseña().contains(contraseña))
            {                              

                          if(tipousuario.getNombreTipoUsuario().contains("ADMINISTRADOR"))
                          {
                              jMTArchivo.setEnabled(true);
                              jMTSueldo.setEnabled(true);
                              jMenu3.setEnabled(true);
                              jMenu4.setEnabled(true);
                              jMenu7.setEnabled(true);
                              jmMapa.setEnabled(true);
                              jMenu6.setEnabled(true);
                              btnLibros.setEnabled(true);
                              btnCliente.setEnabled(true);
                              btnNueVenta.setEnabled(true);
                              jMTSueldo.setEnabled(true);
                        }      
                          
                          if(tipousuario.getNombreTipoUsuario().contains("VENTAS"))
                          {
                            jMTArchivo.setEnabled(true);
                            jMenu4.setEnabled(true);
                            //jMenuItem3.setEnabled(false);
                            btnCliente.setEnabled(true);
                            btnNueVenta.setEnabled(true);
                            
                          }
                          if(tipousuario.getNombreTipoUsuario().contains("COMPRAS"))
                          {
                            jMTArchivo.setEnabled(true);
                            jMenu3.setEnabled(true);
                            jMenu7.setEnabled(true);
                            btnLibros.setEnabled(true);
                            //jbtNueCompra.setEnabled(true);
                            
                          }
            jtfusuario.setVisible(false);
            jPcontraseña.setVisible(false);
            jLcontraseña.setVisible(false);
            jLusuario.setVisible(false);
            jLBienvenidos.setVisible(false);
            jLabel7.setVisible(false);
            jBIngresar.setVisible(false);
            jLElegirOpcion.setVisible(true);
            }
        else
        {
            JOptionPane.showMessageDialog(this,"Contraseña invalida");
            jPcontraseña.requestFocus();
            jPcontraseña.setText("");
        }
        }
        else
        {
                JOptionPane.showMessageDialog(this,"Usuario inexistente");
                jtfusuario.setText("");
                jPcontraseña.setText("");
        }
    }//GEN-LAST:event_jBIngresarActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCambiarUsuarioActionPerformed
        jPanelBase.removeAll();
        jPanelBase.repaint();
        jPanelBase.revalidate();
        //muestro datos de logueo
        jLElegirOpcion.setVisible(false);
            jTUsuarioNuevo.setVisible(false);
            jTcontraseñaNueva.setVisible(false);
            jLRepetir.setVisible(false);
            jTContraseñaRepetida.setVisible(false);
            jBNuevoUsuario.setVisible(false);
            jLNuevoUsuario.setVisible(false);
            jLNuevaContraseña.setVisible(false);
            jLBienvenidos.setVisible(false);
            jBIngresar.setEnabled(true);
            jBIngresar.setVisible(true);
            jLusuario.setVisible(true);
            jtfusuario.setVisible(true);
            jtfusuario.setEnabled(true);
            jtfusuario.setText("");
            jLcontraseña.setVisible(true);
            jPcontraseña.setVisible(true);
            jPcontraseña.setEnabled(true);
            jPcontraseña.setText("");
            jLPrimerIngreso.setVisible(false);
        //Inhabilito todas las funciones
        jMTArchivo.setEnabled(false);
        jMTSueldo.setEnabled(false);
        jMenu3.setEnabled(false);
        jMenu4.setEnabled(false);
        jMenu7.setEnabled(false);
        jMenu6.setEnabled(false);
        jmMapa.setEnabled(false);
        btnLibros.setEnabled(false);
        btnCliente.setEnabled(false);
        btnNueVenta.setEnabled(false);
        jPanelBase.add(jPanel1);
    }//GEN-LAST:event_jMCambiarUsuarioActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       ABMTipoUsuario tu = new ABMTipoUsuario();
       CargarPanel(tu);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jpUsuario tu = new jpUsuario();
        CargarPanel(tu);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jBNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        String contraseña="",contraseñarepetir="" ;
       if (jTcontraseñaNueva.getText().equals("") || jTContraseñaRepetida.getText().equals(""))
       {
            JOptionPane.showMessageDialog(this,"La contraseña no puede ser vacia, verifique los campos de contraseña");
       }
       else
       {
            if (jTcontraseñaNueva.getText().equals(jTContraseñaRepetida.getText()))
            {
                if (consultaUsuario.comprobarContraseña(jTcontraseñaNueva.getText()))
                {
                 if(consultaUsuario.comprobarUsuarioExiste(jTUsuarioNuevo.getText()))
                     {
                        JOptionPane.showMessageDialog(this,"Usuario Existe");
                     }
                 else
                 {
                    contraseña= DigestUtils.md5Hex(jTcontraseñaNueva.getText());
                    Usuario user = new Usuario(0,jTUsuarioNuevo.getText(),contraseña,1);
                    consultaUsuario.agregarUsuario(user);
                    JOptionPane.showMessageDialog(this,"Primer Usuario Administrador Agregado");
                    jTUsuarioNuevo.setVisible(false);
                    jTcontraseñaNueva.setVisible(false);
                    jTContraseñaRepetida.setVisible(false);
                    jBNuevoUsuario.setVisible(false);
                    jLNuevoUsuario.setVisible(false);
                    jLNuevaContraseña.setVisible(false);
                    jLRepetir.setVisible(false);
                    jLPrimerIngreso.setVisible(false);
                    jtfusuario.setText(jTUsuarioNuevo.getText());
                    jPcontraseña.setText("");
                    jBIngresar.setEnabled(true);
                    jtfusuario.setEnabled(true);
                    jPcontraseña.setEnabled(true);
                 }    
                }
                else
                {
                   JOptionPane.showMessageDialog(this,"La contraseña no cumple con los requisitos de seguridad minimos. (Longitud mayor a 5, contener minimo una mayuscula y contener minimo un numero)");
                   jTcontraseñaNueva.setText("");
                   jTContraseñaRepetida.setText("");
                   jTcontraseñaNueva.requestFocus();
                }
            }
            else
            JOptionPane.showMessageDialog(this,"Las contraseñas ingresadas no coinciden");
                
       }
    }//GEN-LAST:event_jBNuevoUsuarioActionPerformed

    private void jMTArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMTArchivoActionPerformed

    private void jmiAutores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAutores1ActionPerformed
        jpAutor pa= new  jpAutor();
        CargarPanel(pa);        
    }//GEN-LAST:event_jmiAutores1ActionPerformed

    private void jmiGeneros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGeneros1ActionPerformed
        jpGenero pg= new  jpGenero();
        CargarPanel(pg);          
    }//GEN-LAST:event_jmiGeneros1ActionPerformed

    private void jmiEditoriales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditoriales1ActionPerformed
        jpEditorial pe= new  jpEditorial();
       CargarPanel(pe);        
    }//GEN-LAST:event_jmiEditoriales1ActionPerformed

    private void jmiProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProveedorActionPerformed
        jpProveedores pp= new  jpProveedores(0);
        CargarPanel(pp);
    }//GEN-LAST:event_jmiProveedorActionPerformed

    private void jmiPedidoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPedidoManualActionPerformed
        jpNuevoPedido tf= new jpNuevoPedido(0);
        CargarPanel(tf);
    }//GEN-LAST:event_jmiPedidoManualActionPerformed

    private void jmiPedidoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPedidoAutoActionPerformed
        jpNuevoPedido tf= new jpNuevoPedido(1);
        CargarPanel(tf);
    }//GEN-LAST:event_jmiPedidoAutoActionPerformed

    private void jmiListaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListaPedidoActionPerformed
        jpListaPedidos tf= new jpListaPedidos(1);
        CargarPanel(tf);
    }//GEN-LAST:event_jmiListaPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnNueVenta;
    private javax.swing.JButton jBIngresar;
    private javax.swing.JButton jBNuevoUsuario;
    private javax.swing.JLabel jLBienvenidos;
    private javax.swing.JLabel jLElegirOpcion;
    private javax.swing.JLabel jLNuevaContraseña;
    private javax.swing.JLabel jLNuevoUsuario;
    private javax.swing.JLabel jLPrimerIngreso;
    private javax.swing.JLabel jLRepetir;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLcontraseña;
    private javax.swing.JLabel jLusuario;
    private javax.swing.JMenuItem jMCambiarUsuario;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMTArchivo;
    private javax.swing.JMenu jMTSueldo;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelBtn;
    private javax.swing.JPasswordField jPcontraseña;
    private javax.swing.JPasswordField jTContraseñaRepetida;
    private javax.swing.JTextField jTUsuarioNuevo;
    private javax.swing.JPasswordField jTcontraseñaNueva;
    private javax.swing.JMenuItem jmCategorias;
    private javax.swing.JMenuItem jmEmpleados;
    private javax.swing.JMenuItem jmEstadosCiviles;
    private javax.swing.JMenu jmMapa;
    private javax.swing.JMenu jmNuevoPedido;
    private javax.swing.JMenu jmPedidos;
    private javax.swing.JMenuItem jmiAutores1;
    private javax.swing.JMenuItem jmiEditoriales1;
    private javax.swing.JMenuItem jmiGeneros1;
    private javax.swing.JMenuItem jmiListaPedido;
    private javax.swing.JMenuItem jmiLocalidades;
    private javax.swing.JMenuItem jmiPedidoAuto;
    private javax.swing.JMenuItem jmiPedidoManual;
    private javax.swing.JMenuItem jmiProveedor;
    private javax.swing.JMenuItem jmiProvincia;
    private javax.swing.JTextField jtfusuario;
    // End of variables declaration//GEN-END:variables
}
